name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout to prevent broken pipe issues

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Buildozer and python-for-android
      run: |
        pip install --upgrade pip || true
        pip install buildozer python-for-android cython || true

    - name: Clean Buildozer
      run: |
        buildozer android clean || true

    - name: Build Android App
      run: |
        buildozer -v android debug
