name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # Use Java 8
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Buildozer and python-for-android
      run: |
        pip install --upgrade pip || true
        pip install buildozer python-for-android cython || true

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses || true
        yes | $HOME/android-sdk/tools/bin/sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-31"

    - name: Clean Buildozer
      run: |
        buildozer android clean || true

    - name: Build Android App
      run: |
        buildozer -v android debug | tee build_output.log

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-android-app
       path: ${{ steps.buildozer.outputs.filename }}

