name: Build Android App

on: 
  push:
    branches:
      - main  # or the branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # Use Java 8
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Buildozer and python-for-android
        run: |
          pip install --upgrade pip || true
          pip install buildozer python-for-android cython || true

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip sdk-tools-linux-4333796.zip
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Set Environment Variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

      - name: Clean Buildozer
        run: |
          buildozer android clean || true

      - name: Build Android App
        run: |
          buildozer -v android debug | tee build_output.log

      - name: List APKs
        run: |
          ls -la bin/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: bin/*.apk
