name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use the appropriate version for your project
        distribution: 'adopt'

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/Android/Sdk
        export ANDROID_HOME=$HOME/Android/Sdk
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        curl -sL https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -o sdk-tools.zip
        unzip sdk-tools.zip -d $ANDROID_HOME
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Buildozer and python-for-android
      run: |
        pip install --upgrade pip
        pip install buildozer python-for-android cython

    - name: Clean Buildozer
      run: |
        buildozer android clean || true

    - name: Build Android App
      run: |
        buildozer -v android debug
