name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout to prevent broken pipe issues

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the required Java version
        distribution: 'temurin'  # Use the Temurin distribution

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Buildozer and python-for-android
      run: |
        pip install --upgrade pip || true
        pip install buildozer python-for-android cython || true

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses  # Accept licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;31.0.0"  # Specify the build tools version

    - name: Clean Buildozer
      run: |
        buildozer android clean || true

    - name: Build Android App
      run: |
        buildozer -v android debug
