name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Buildozer and python-for-android
      run: |
        pip install --upgrade pip
        pip install buildozer python-for-android cython

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;31.0.0"

    - name: Clean Buildozer
      run: |
        buildozer android clean

    - name: Build Android App
      run: |
        buildozer -v android debug | tee build_output.log

    - name: List APKs
      run: |
        ls -la bin/
