name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libssl-dev libffi-dev python3-dev openjdk-11-jdk zip unzip
        pip install --upgrade pip
        pip install buildozer python-for-android cython

    - name: Install Android SDK Command-Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        rm commandlinetools-linux-7583922_latest.zip
        mv cmdline-tools/* ./
        rmdir cmdline-tools  # Remove the now-empty directory

        # Set SDK root and PATH
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept SDK Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install SDK Components
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-31" "build-tools;30.0.3"

    - name: Clean Buildozer
      run: buildozer android clean || true

    - name: Build Android App
      run: buildozer -v android debug | tee build_output.log

    - name: Check for APK
      run: |
        echo "Searching for APK files in ./bin:"
        find ./bin -name "*.apk" || echo "No APK files found."

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-android-app
        path: ./bin/project-0.1-debug.apk  # Path based on your spec file
        if-no-files-found: error
        include-hidden-files: false
