name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer python-for-android

    - name: Clean Buildozer
      run: |
        buildozer android clean

    - name: Build Android App
      run: |
        buildozer -v android debug
